### ISSUE TITLE
Two SSL-related pynntp pytests fail

### ISSUE THREAD

**Issue by cclauss** [cclauss/apt-get-inn2-docker#6]
https://github.com/cclauss/apt-get-inn2-docker/actions/runs/11018800364/job/30599897391#step:8:121
```
=========================== short test summary info ============================
FAILED tests/integration/inn2/test_inn2.py::test_nntp_client_with_ssl - ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)
FAILED tests/integration/inn2/test_inn2.py::test_nntp_client_with_ssl_starttls - nntp.nntp.NNTPPermanentError: 580 Error initializing TLS
=================== 2 failed, 38 passed, 14 xfailed in 1.47s ===================
```
@greenbender, do you have any insight into how to fix these two failing tests?
* `Generating SSL key` startup step is missing.

This repo tries to be as close to yours but is built on `debian:bookworm` and uses `apt-get install inn2`.

---
% `docker build --no-cache --progress plain -t inn . && docker run --rm -it -p119:119 -p563:563 inn`

> #10 12.58 Setting up inn2-inews (2.7.1-1+deb12u1) ...
#10 12.58
#10 12.58 Configuration file '/etc/news/inn.conf'
#10 12.58  ==> File on system created by you or by a script.
#10 12.58  ==> File also in package provided by package maintainer.
#10 12.58  ==> Using current old file as you requested.
[ ... ]
#10 13.65 Setting up openssl (3.0.14-1~deb12u2) ...
[ ... ]
#10 13.80 Setting up ca-certificates (20230311) ...
[ ... ]
#10 14.74 Setting up inn2 (2.7.1-1+deb12u1) ...
#10 14.80
#10 14.80 Configuration file '/etc/news/readers.conf'
#10 14.80  ==> File on system created by you or by a script.
#10 14.80  ==> File also in package provided by package maintainer.
#10 14.80  ==> Using current old file as you requested.
#10 14.81 Installing initial content for /var/lib/news/active
#10 14.81 Installing initial content for /var/lib/news/newsgroups
#10 14.81 Building history database in /var/lib/news... makehistory: tradspool: mapping file /var/spool/news/tradspool.map not found

**Comment by cclauss** [comment]
# docker run --rm -t -p119:119 -p563:563 greenbender/inn
```
Generating SSL key
.+..+....+.....+....+..+....+...+...+...+..+....+++++++++++++++++++++++++++++++++++++++++++++*......+++++++++++++++++++++++++++++++++++++++++++++*.............+..+.......+......+......+.....+...+...+...+.+........+..........+..........................+.......+.........+.....+.+........+++++
..........+..+.......+..+...+++++++++++++++++++++++++++++++++++++++++++++*.............+..+......+.+.....+.........+....+++++++++++++++++++++++++++++++++++++++++++++*....+...........+....+...+...+........................+............+.........+...........+.+.........+...+.....+...+.............+...........+.+.....+....+...+......+..+++++
-----
innd: SERVER descriptors 1023
innd: SERVER outgoing 1010
innd: SERVER ccsetup control:12
innd: SERVER lcsetup localconn:14
innd: SERVER rcsetup remconn:15
innd: SERVER rcsetup remconn:17
innd: controlchan! spawned controlchan!:21:proc:27
innd: tradspool: mapping file /usr/local/news/spool/tradspool.map not found
innd: SERVER starting
```
---
# docker run --rm -t -p119:119 -p563:563 cclauss/inn
```
innd: SERVER descriptors 1023
innd: SERVER outgoing 1010
innd: SERVER ccsetup control:11
innd: SERVER lcsetup localconn:13
innd: SERVER rcsetup remconn:14
innd: controlchan! spawned controlchan!:18:proc:23
innd: SERVER perl filtering enabled
innd: pyfilter /etc/news/filter/filter_innd.py not installed
innd: SERVER Python filtering disabled
innd: SERVER starting
```

**Comment by greenbender** [comment]
You need to generate proper ssl key/cert for inn to use... I'll see if I can prepoduce the issue and create a fix
